---
Name: apiroutes
---
SilverStripe\Control\Director:
  rules:
    'park/$ID//$action': 'PageController'
    'api/v1/parks/$ID//$action': 'Doggo\Controller\ParkController'
    'api/v1/upload': 'Doggo\Controller\ImageUploadController'